### ISSUE TITLE
Remove all base64 encoded svg+xml

### ISSUE THREAD

**Issue by gnarf** [iros/patternfills#2]
Base64 takes more characters than plain text.  XML can be transferred in plain ascii, so you can do this:

``` css
.crosshatch {
  background-image: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' width='8' height='8'><rect width='8' height='8' fill='#fff'/><path d='M0 0L8 8ZM8 0L0 8Z' stroke-width='0.5' stroke='#aaa'/></svg>");
}
/* compare in scrollbar distance to: */
.crosshatch {
  background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPSc4JyBoZWlnaHQ9JzgnPgogIDxyZWN0IHdpZHRoPSc4JyBoZWlnaHQ9JzgnIGZpbGw9JyNmZmYnLz4KICA8cGF0aCBkPSdNMCAwTDggOFpNOCAwTDAgOFonIHN0cm9rZS13aWR0aD0nMC41JyBzdHJva2U9JyNhYWEnLz4KPC9zdmc+Cg==");
}
```

http://jsbin.com/hepo/1/edit?css,output
Also, gzip will love the plain text version.

The build step would need to:
- [ ] remove all "unnecessary white space" between the tags in the source,
- [ ] replace all `/\s+/` with a single space (in case any newlines survive the former clean up).
- [ ] normalize all of the quotes in the svg to either single or double then use the opposite outside to quote the url, adding a `\` to a quote if it must.

Hoping I might find some time to play with this (not at 1:30am), so I'm leaving myself this note :)

Also, will need to replace `/\s+/` with a space, and remove all .
